#!/bin/bash
#OpenAM Shell REST Client
#sudo chmod 400 once set!

#URL Protocol of OpenAM server. (HTTP or HTTPS)
PROTOCOL=HTTP 

#FQDN
OPENAM_SERVER=openam.example.com 

#Server Port. (8080)
OPENAM_SERVER_PORT=8081

#Returning data format. (xml or json)
FORMAT=json

#Admin user authentication token.  Required when running user create/read/delete scripts etc.  Generate using ./authenticate_user_password.sh
ADMIN_TOKEN=AQIC5wM2LY4SfczxAyD7i8G07gxlUPjmNzRObv7yxOqmiE8.*AAJTSQACMDEAAlNLABM2MTIwODU0MzQ1OTU3ODA4MDYw*

